[phases.setup]
nixPkgs = [
  "nodejs-18_x",
  "python39",
  "python39Packages.pip"
]

[phases.install]
cmds = [
  "python -m pip install --upgrade pip",
  "pip install -r requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT" 