[phases.setup]
nixPkgs = [
  "python3",
  "python3.pkgs.pip",
  "nodejs-18_x"
]

[phases.install]
cmds = [
  "python3 -m pip install --upgrade pip",
  "pip install -r requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
cmds = ["cd frontend && npm run build"]

[start]
cmd = "python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT" 