[variables]
PYTHON_VERSION = "3.9"
NODE_VERSION = "18.17.0"

[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y python3-pip nodejs npm"
]

[phases.install]
cmds = [
    "python3 -m pip install --upgrade pip",
    "pip install -r requirements.txt",
    "cd frontend && npm install"
]

[phases.build]
cmds = [
    "cd frontend && npm run build"
]

[start]
cmd = "python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT" 