[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100

[nixpacks]
start-command = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT" 