[build]
builder = "nixpacks"

[variables]
NIXPACKS_PYTHON_VERSION = "3.9"
NIXPACKS_NODE_VERSION = "18.17.0"
PYTHON_VERSION = "3.9"
NODE_VERSION = "18.17.0"

[deploy]
startCommand = "python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 100

[phases.setup]
nixPkgs = ["python3", "nodejs"] 